version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout

      - run:
          name: Add SDK 28
          command: echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-28"

      - run:
          name: spotless check
          command: ./gradlew spotlessCheck

      - run:
          name: Build test
          command: ./gradlew build

      - run:
          name: spotless apply
          command: ./gradlew spotlessApply
